/**
 * Prebuilt OpenStreetMap building footprints for the 3D viewer.
 *
 * The manifest is generated by scripts/fetch-building-footprints.ts and
 * committed, so the viewer can draw a building without waiting 5-15s on a
 * public Overpass server. Outlines and tags come from OpenStreetMap
 * (© OpenStreetMap contributors, ODbL, https://www.openstreetmap.org/copyright);
 * the viewer credits them next to the model.
 *
 * Keyed by building name, NOT database id: ids differ between the prod,
 * staging, and e2e databases (same reasoning as landmark-images.json).
 * A `null` entry means Overpass was asked and had no building there, so the
 * viewer can go straight to its approximate box. A missing key means the
 * script never saw that building, and the viewer falls back to Overpass.
 */
import manifest from "@constants/building-footprints.json";
import { isFootprint, type OsmBuildingFootprint } from "./overpass";

export type BuildingFootprintsManifest = Record<
  string,
  OsmBuildingFootprint | null
>;

/**
 * `undefined` when the manifest has no entry (ask Overpass), `null` when OSM
 * is known to have no footprint, else the footprint.
 */
export function bundledFootprint(
  buildingName: string,
  source: Record<string, unknown> = manifest,
): OsmBuildingFootprint | null | undefined {
  if (!Object.hasOwn(source, buildingName)) return undefined;
  const entry = source[buildingName];
  if (entry === null) return null;
  return isFootprint(entry) ? entry : undefined;
}
