/**
 * Landmark photo galleries (1-10 images per landmark, multiple sources).
 *
 * The manifest is generated by scripts/fetch-landmark-images.ts and committed:
 * Wikimedia Commons photos are hotlinked with the attribution their licenses
 * require, and Street View is stored only as compass headings — the client
 * builds URLs with its own key because Google's terms forbid storing imagery.
 */
import manifest from "@constants/landmark-images.json";
import {
  STREET_VIEW_ATTRIBUTION,
  hasStreetViewKey,
  streetViewImageUrl,
} from "./street-view";

export type CommonsImage = {
  /** Direct thumbnail URL on upload.wikimedia.org (hotlinking is supported). */
  url: string;
  /** File page, where the full attribution lives. */
  pageUrl: string;
  artist: string;
  license: string;
};

export type LandmarkImagesEntry = {
  /** Street View facade headings: center on the building, one to each side. */
  streetViewHeadings?: number[];
  commons?: CommonsImage[];
};

/**
 * Keyed `building:<buildingName>`, NOT by database id: ids differ between the
 * prod, staging, and e2e databases, and an id-keyed manifest would silently
 * hang the wrong photos on the wrong buildings everywhere but prod (the same
 * failure mode as the dorm id-matching incident, PR #764). A name that
 * misses just means no gallery.
 */
export type LandmarkImagesManifest = Record<string, LandmarkImagesEntry>;

/** Total images per landmark the UI may show, all sources combined. */
export const MAX_IMAGES_PER_LANDMARK = 10;
export const MAX_COMMONS_IMAGES = 7;

export type LandmarkImage = {
  src: string;
  alt: string;
  /** "Street View image © Google" / "Juan D (CC BY-SA 4.0)". Absent for contributor photos. */
  credit?: string;
  /** Where the credit should link (Commons file page). */
  creditUrl?: string;
  source: "contributor" | "street-view" | "commons";
};

const LANDMARK_IMAGES = manifest as LandmarkImagesManifest;

export type BuildingImagesInput = {
  name: string;
  imageUrl?: string | null;
  lat?: number | null;
  lon?: number | null;
  /** Cached Street View lookup (migration 0052). Null means no coverage. */
  panoId?: string | null;
  googleKey?: string;
};

/**
 * Every image the panel can show for a building, in display order:
 * contributor photo first (ours, current, chosen to show the entrance), then
 * Street View facade angles, then Commons photos. Capped at
 * MAX_IMAGES_PER_LANDMARK; empty when no source has anything.
 */
export function buildingLandmarkImages(
  input: BuildingImagesInput,
): LandmarkImage[] {
  const { name, imageUrl, lat, lon, panoId, googleKey } = input;
  const entry = LANDMARK_IMAGES[`building:${name}`];
  const images: LandmarkImage[] = [];

  if (imageUrl) {
    images.push({ src: imageUrl, alt: name, source: "contributor" });
  }

  if (hasStreetViewKey(googleKey) && panoId && lat != null && lon != null) {
    // No manifest entry still gets the pre-gallery single shot: Google points
    // the camera at the subject when no heading is given.
    const headings = entry?.streetViewHeadings ?? [undefined];
    for (const heading of headings) {
      images.push({
        src: streetViewImageUrl(
          { lat: Number(lat), lng: Number(lon) },
          googleKey,
          {
            width: 640,
            height: 360,
            // Wider than the default so more of the frontage fits, and enough
            // radius to reach buildings set back from the road.
            fov: 90,
            radius: 100,
            heading,
          },
        ),
        alt: `Street View of ${name}`,
        credit: STREET_VIEW_ATTRIBUTION,
        source: "street-view",
      });
    }
  }

  for (const photo of entry?.commons ?? []) {
    images.push({
      src: photo.url,
      alt: `${name} (photo via Wikimedia Commons)`,
      credit: `${photo.artist} (${photo.license})`,
      creditUrl: photo.pageUrl,
      source: "commons",
    });
  }

  return images.slice(0, MAX_IMAGES_PER_LANDMARK);
}
