/**
 * Landmark photo galleries (1-10 images per landmark, multiple sources).
 *
 * The manifest is generated by scripts/fetch-landmark-images.ts and committed:
 * Wikimedia Commons photos are hotlinked with the attribution their licenses
 * require, and Street View is stored only as compass headings — the client
 * builds URLs with its own key because Google's terms forbid storing imagery.
 * Entities the manifest misses (food spots, stores, newer pins) get one
 * Street View shot from a runtime metadata lookup (street-view-lookup.ts).
 */
import manifest from "@constants/landmark-images.json";
import {
  STREET_VIEW_ATTRIBUTION,
  hasStreetViewKey,
  streetViewImageUrl,
} from "./street-view";
import type { StreetViewPano } from "./street-view-lookup";

export type CommonsImage = {
  /** Direct thumbnail URL on thumb/upload.wikimedia.org (hotlinking is supported). */
  url: string;
  /** File page, where the full attribution lives. */
  pageUrl: string;
  artist: string;
  license: string;
};

export type LandmarkImagesEntry = {
  /** Street View facade headings: center on the building, one to each side. */
  streetViewHeadings?: number[];
  /**
   * The panorama the headings were computed from. Pinned so the client shows
   * that pano, not whichever one Google finds nearest at render time.
   */
  streetViewPanoId?: string;
  /**
   * Set when the pano is a photo sphere somebody uploaded to Google (often a
   * classroom or lobby), not Google's own capture: the uploader's credit
   * line ("© Ry Clark Media Arts"). Those panos are shown last.
   */
  streetViewCopyright?: string;
  commons?: CommonsImage[];
};

/**
 * Keyed `<kind>:<name>` (`building:<buildingName>`, `dorm:<dormName>`,
 * `place:<name>`, `organization:<name>`), NOT by database id: ids differ between the
 * prod, staging, and e2e databases, and an id-keyed manifest would silently
 * hang the wrong photos on the wrong buildings everywhere but prod (the same
 * failure mode as the dorm id-matching incident, PR #764). A name that
 * misses just means no gallery.
 */
export type LandmarkImagesManifest = Record<string, LandmarkImagesEntry>;

/** Total images per landmark the UI may show, all sources combined. */
export const MAX_IMAGES_PER_LANDMARK = 10;
export const MAX_COMMONS_IMAGES = 7;

export type LandmarkImage = {
  src: string;
  alt: string;
  /** "Street View image © Google" / "Juan D (CC BY-SA 4.0)". Absent for contributor photos. */
  credit?: string;
  /** Where the credit should link (Commons file page). */
  creditUrl?: string;
  source: "contributor" | "street-view" | "commons";
};

const LANDMARK_IMAGES = manifest as LandmarkImagesManifest;

export type LandmarkKind = "building" | "dorm" | "place" | "organization";

export type LandmarkImagesInput = {
  /** Manifest key prefix. Defaults to "building". */
  kind?: LandmarkKind;
  name: string;
  imageUrl?: string | null;
  lat?: number | null;
  lon?: number | null;
  /** Cached Street View lookup (migration 0052). Null means no coverage. */
  panoId?: string | null;
  googleKey?: string;
  /**
   * Runtime metadata lookup (street-view-lookup.ts) for an entity with no
   * manifest entry and no cached pano: pinned pano, aimed at the place.
   */
  lookedUpPano?: StreetViewPano | null;
};

/**
 * True when only a runtime lookup can find Street View for this entity: a
 * key, coordinates, no manifest entry, and no cached pano from the caller
 * (`panoId: null` is a cached "no coverage", so it skips the request too).
 */
export function needsStreetViewLookup(input: LandmarkImagesInput): boolean {
  const { kind = "building", name, lat, lon, panoId, googleKey } = input;
  return (
    hasStreetViewKey(googleKey) &&
    lat != null &&
    lon != null &&
    panoId === undefined &&
    !LANDMARK_IMAGES[`${kind}:${name}`]
  );
}

/**
 * Every image the panel can show for a landmark, in display order: Google's
 * own Street View facade angles first (the thumbnail), then the contributor
 * photo, then Commons photos, and a pano somebody uploaded to Google last. Capped at
 * MAX_IMAGES_PER_LANDMARK; empty when no source has anything.
 */
export function landmarkImages(input: LandmarkImagesInput): LandmarkImage[] {
  const { kind = "building", name, imageUrl, lat, lon, googleKey } = input;
  const manifestEntry = LANDMARK_IMAGES[`${kind}:${name}`];
  const lookedUp = manifestEntry ? null : input.lookedUpPano;
  // A looked-up pano slots in as a one-heading manifest entry, so ordering and
  // uploader credit follow the same rules.
  const entry: LandmarkImagesEntry | undefined = lookedUp
    ? {
        streetViewPanoId: lookedUp.panoId,
        streetViewHeadings:
          lookedUp.heading === undefined ? undefined : [lookedUp.heading],
        streetViewCopyright:
          lookedUp.copyright && !/google/i.test(lookedUp.copyright)
            ? lookedUp.copyright
            : undefined,
      }
    : manifestEntry;
  // A pinned manifest pano is itself proof of coverage: the fetch script only
  // records one after the free metadata check found it.
  const panoId = entry?.streetViewPanoId ?? input.panoId;
  const streetView: LandmarkImage[] = [];

  if (hasStreetViewKey(googleKey) && panoId && lat != null && lon != null) {
    // No manifest entry still gets the pre-gallery single shot: Google points
    // the camera at the subject when no heading is given.
    const headings = entry?.streetViewHeadings ?? [undefined];
    for (const heading of headings) {
      streetView.push({
        src: streetViewImageUrl(
          { lat: Number(lat), lng: Number(lon) },
          googleKey,
          {
            width: 640,
            height: 360,
            // Wider than the default so more of the frontage fits, and enough
            // radius to reach buildings set back from the road.
            fov: 90,
            radius: 100,
            heading,
            pano: entry?.streetViewPanoId,
          },
        ),
        alt: `Street View of ${name}`,
        credit: entry?.streetViewCopyright
          ? `Street View image ${entry.streetViewCopyright}`
          : STREET_VIEW_ATTRIBUTION,
        source: "street-view",
      });
    }
  }

  const uploadedPano = Boolean(entry?.streetViewCopyright);
  const images: LandmarkImage[] = uploadedPano ? [] : [...streetView];
  if (imageUrl) {
    images.push({ src: imageUrl, alt: name, source: "contributor" });
  }

  for (const photo of entry?.commons ?? []) {
    images.push({
      src: photo.url,
      alt: `${name} (photo via Wikimedia Commons)`,
      credit: `${photo.artist} (${photo.license})`,
      creditUrl: photo.pageUrl,
      source: "commons",
    });
  }

  if (uploadedPano) images.push(...streetView);

  return images.slice(0, MAX_IMAGES_PER_LANDMARK);
}
