# GitHub Sponsors funding model — links to our donation and sponsorship pages.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [uplbtools]
custom:
  [
    "https://room-tba.uplbtools.me/donate",
    "https://room-tba.uplbtools.me/sponsors",
  ]
