-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "buildings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "buildings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"building_name" varchar(100) NOT NULL,
	"lon" numeric NOT NULL,
	"lat" numeric NOT NULL,
	"directions" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "colleges" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "colleges_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"college_name" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "classes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "classes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"course_code" varchar(16),
	"section" varchar(16),
	"type" varchar(12),
	"schedule" text[],
	"room_id" integer,
	"course_title" text,
	"term_id" integer
);
--> statement-breakpoint
CREATE TABLE "dorms" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dorms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"dorm_name" text NOT NULL,
	"short_name" varchar(48),
	"lat" numeric,
	"lon" numeric,
	"gender" text NOT NULL,
	"capacity" integer,
	"managing_office" text,
	"contact_email" text,
	"amenities" text[],
	"osm_link" text,
	"description" text,
	"is_up_managed" boolean DEFAULT true,
	"price_range" text,
	"contact_phone" varchar(20)[],
	"facebook_link" text
);
--> statement-breakpoint
CREATE TABLE "room_positions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "room_positions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"floor" integer NOT NULL,
	"pos_x" numeric NOT NULL,
	"pos_y" numeric NOT NULL,
	"updated_at" timestamp NOT NULL,
	"room_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "divisions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "divisions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"division_name" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rooms" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rooms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"room_code" text NOT NULL,
	"directions" text,
	"building_id" integer,
	"college_id" integer,
	"division_id" integer
);
--> statement-breakpoint
ALTER TABLE "classes" ADD CONSTRAINT "class_room" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "room_positions" ADD CONSTRAINT "room_position_id" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rooms" ADD CONSTRAINT "room_building" FOREIGN KEY ("building_id") REFERENCES "public"."buildings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rooms" ADD CONSTRAINT "room_college" FOREIGN KEY ("college_id") REFERENCES "public"."colleges"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rooms" ADD CONSTRAINT "room_division" FOREIGN KEY ("division_id") REFERENCES "public"."divisions"("id") ON DELETE no action ON UPDATE no action;
*/
