CREATE TYPE "public"."contributor_profile_audit_action" AS ENUM('create', 'update', 'publish', 'hide', 'restore', 'remove_link');--> statement-breakpoint
CREATE TYPE "public"."contributor_social_kind" AS ENUM('github', 'website', 'discord', 'messenger', 'linkedin', 'custom');--> statement-breakpoint
CREATE TABLE "contributor_profile_audits" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contributor_profile_audits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"profile_id" integer NOT NULL,
	"actor_user_id" integer,
	"action" "contributor_profile_audit_action" NOT NULL,
	"from_version" integer,
	"to_version" integer NOT NULL,
	"before" jsonb,
	"after" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contributor_profiles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contributor_profiles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"slug" varchar(120) NOT NULL,
	"bio" varchar(280) DEFAULT '' NOT NULL,
	"is_public" boolean DEFAULT true NOT NULL,
	"is_moderator_hidden" boolean DEFAULT false NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "contributor_profiles_bio_length" CHECK (char_length("contributor_profiles"."bio") <= 280)
);
--> statement-breakpoint
CREATE TABLE "contributor_social_links" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contributor_social_links_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"profile_id" integer NOT NULL,
	"kind" "contributor_social_kind" NOT NULL,
	"label" varchar(40),
	"url" varchar(2048) NOT NULL,
	"is_public" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "contributor_social_links_https_url" CHECK ("contributor_social_links"."url" ~ '^https://'),
	CONSTRAINT "contributor_social_links_custom_label" CHECK ("contributor_social_links"."kind" <> 'custom' OR ("contributor_social_links"."label" IS NOT NULL AND char_length(trim("contributor_social_links"."label")) > 0))
);
--> statement-breakpoint
ALTER TABLE "contributor_profile_audits" ADD CONSTRAINT "contributor_profile_audits_profile_id_contributor_profiles_id_fk" FOREIGN KEY ("profile_id") REFERENCES "public"."contributor_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contributor_profile_audits" ADD CONSTRAINT "contributor_profile_audits_actor_user_id_admin_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."admin_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contributor_profiles" ADD CONSTRAINT "contributor_profiles_user_id_admin_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."admin_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contributor_social_links" ADD CONSTRAINT "contributor_social_links_profile_id_contributor_profiles_id_fk" FOREIGN KEY ("profile_id") REFERENCES "public"."contributor_profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "contributor_profile_audits_profile_created_idx" ON "contributor_profile_audits" USING btree ("profile_id","created_at");--> statement-breakpoint
CREATE INDEX "contributor_profile_audits_actor_idx" ON "contributor_profile_audits" USING btree ("actor_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "contributor_profiles_user_id_unique" ON "contributor_profiles" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "contributor_profiles_slug_unique" ON "contributor_profiles" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "contributor_social_links_profile_idx" ON "contributor_social_links" USING btree ("profile_id");--> statement-breakpoint
CREATE UNIQUE INDEX "contributor_social_links_known_kind_unique" ON "contributor_social_links" USING btree ("profile_id","kind") WHERE "contributor_social_links"."kind" in ('github', 'discord', 'messenger', 'linkedin');
WITH eligible AS (
	SELECT
		id,
		CASE
			WHEN regexp_replace(regexp_replace(lower(trim(username)), '[^a-z0-9]+', '-', 'g'), '(^-+|-+$)', '', 'g') = '' THEN 'contributor'
			ELSE left(regexp_replace(regexp_replace(lower(trim(username)), '[^a-z0-9]+', '-', 'g'), '(^-+|-+$)', '', 'g'), 100)
		END AS base_slug
	FROM "admin_users"
	WHERE is_active = true AND deleted_at IS NULL
), candidates AS (
	SELECT
		id,
		CASE
			WHEN count(*) OVER (PARTITION BY base_slug) > 1
			THEN base_slug || '-' || substr(md5(id::text), 1, 8)
			ELSE base_slug
		END AS slug
	FROM eligible
), inserted AS (
	INSERT INTO "contributor_profiles" ("user_id", "slug", "bio", "is_public", "is_moderator_hidden", "version")
	SELECT id, slug, '', true, false, 1
	FROM candidates
	WHERE NOT EXISTS (
		SELECT 1 FROM "contributor_profiles" existing WHERE existing.user_id = candidates.id
	)
	ON CONFLICT DO NOTHING
	RETURNING "id", "slug", "bio", "is_public", "is_moderator_hidden", "version"
)
INSERT INTO "contributor_profile_audits" ("profile_id", "action", "to_version", "before", "after")
SELECT
	id,
	'create',
	version,
	NULL,
	jsonb_build_object(
		'slug', slug,
		'bio', bio,
		'is_public', is_public,
		'is_moderator_hidden', is_moderator_hidden,
		'version', version
	)
FROM inserted;