DO $$ BEGIN
 CREATE TYPE "public"."event_category" AS ENUM('tradition', 'fair', 'ceremony', 'sports', 'other');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."event_recurrence" AS ENUM('none', 'annual', 'every_1st_sem', 'every_2nd_sem');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."event_location_anchor" AS ENUM('building', 'dorm', 'custom');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" varchar(120) NOT NULL,
	"title" varchar(160) NOT NULL,
	"description" text,
	"category" "event_category" DEFAULT 'other' NOT NULL,
	"starts_at" timestamp NOT NULL,
	"ends_at" timestamp NOT NULL,
	"timezone" varchar(64) DEFAULT 'Asia/Manila' NOT NULL,
	"recurrence" "event_recurrence" DEFAULT 'none' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"source_url" text,
	"priority" integer DEFAULT 0 NOT NULL,
	"include_in_seo" boolean DEFAULT false NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "events_slug_unique" ON "events" USING btree ("slug");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_locations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_locations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_id" integer NOT NULL,
	"anchor_type" "event_location_anchor" NOT NULL,
	"building_id" integer,
	"dorm_id" integer,
	"label" text NOT NULL,
	"lat" double precision,
	"lon" double precision,
	"highlight_priority" integer DEFAULT 0 NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "event_location_event" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action,
	CONSTRAINT "event_location_building" FOREIGN KEY ("building_id") REFERENCES "public"."buildings"("id") ON DELETE no action ON UPDATE no action,
	CONSTRAINT "event_location_dorm" FOREIGN KEY ("dorm_id") REFERENCES "public"."dorms"("id") ON DELETE no action ON UPDATE no action
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_routes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_routes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"event_id" integer NOT NULL,
	"name" varchar(120) NOT NULL,
	"description" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "event_route_event" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE no action ON UPDATE no action
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "event_route_stops" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_route_stops_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"route_id" integer NOT NULL,
	"event_location_id" integer,
	"label" text NOT NULL,
	"lat" double precision,
	"lon" double precision,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "event_route_stop_route" FOREIGN KEY ("route_id") REFERENCES "public"."event_routes"("id") ON DELETE no action ON UPDATE no action,
	CONSTRAINT "event_route_stop_location" FOREIGN KEY ("event_location_id") REFERENCES "public"."event_locations"("id") ON DELETE no action ON UPDATE no action
);
--> statement-breakpoint
INSERT INTO "update" ("table_name")
VALUES ('events'), ('event_locations'), ('event_routes'), ('event_route_stops')
ON CONFLICT DO NOTHING;
