CREATE TABLE IF NOT EXISTS "aliases" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "aliases_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
  "alias" text NOT NULL,
  "normalized_alias" text NOT NULL,
  "target_type" varchar(16) NOT NULL,
  "target_id" integer NOT NULL,
  "source" varchar(32),
  "confidence" varchar(16) NOT NULL DEFAULT 'unverified',
  "created_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "aliases_normalized_target"
  ON "aliases" ("normalized_alias", "target_type", "target_id");
