CREATE TABLE IF NOT EXISTS "admin_users" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
    sequence name "admin_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1
  ),
  "username" varchar(64) NOT NULL,
  "display_name" varchar(100),
  "password_hash" text NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "admin_users_username_unique" ON "admin_users" ("username");
