DO $$ BEGIN
  CREATE TYPE "admin_role" AS ENUM ('admin', 'editor', 'contributor');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "edit_proposal_status" AS ENUM (
    'pending',
    'approved',
    'rejected',
    'needs_changes'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "admin_users"
  ADD COLUMN IF NOT EXISTS "role" "admin_role" DEFAULT 'editor' NOT NULL;

UPDATE "admin_users" SET "role" = 'admin' WHERE "username" = 'admin';

CREATE TABLE IF NOT EXISTS "edit_proposals" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
    sequence name "edit_proposals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1
  ),
  "entity_type" varchar(32) NOT NULL,
  "entity_id" integer NOT NULL,
  "status" "edit_proposal_status" DEFAULT 'pending' NOT NULL,
  "proposed_patch" jsonb NOT NULL,
  "base_version" integer NOT NULL,
  "submitter_name" varchar(100) NOT NULL,
  "submitter_user_id" integer,
  "admin_note" text,
  "reviewed_by" varchar(100),
  "reviewed_at" timestamp,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL,
  CONSTRAINT "edit_proposals_submitter_user_id_admin_users_id_fk"
    FOREIGN KEY ("submitter_user_id") REFERENCES "admin_users"("id")
);

CREATE INDEX IF NOT EXISTS "edit_proposals_status_created_idx"
  ON "edit_proposals" ("status", "created_at" DESC);

CREATE INDEX IF NOT EXISTS "edit_proposals_entity_idx"
  ON "edit_proposals" ("entity_type", "entity_id");
