CREATE TABLE IF NOT EXISTS "final_exams" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
    sequence name "final_exams_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1
  ),
  "term_id" integer NOT NULL,
  "course_code" varchar(16) NOT NULL,
  "section" varchar(16),
  "course_title" text,
  "room_id" integer,
  "exam_date" date NOT NULL,
  "starts_at" time NOT NULL,
  "ends_at" time NOT NULL,
  "source" varchar(64) NOT NULL,
  "version" integer NOT NULL DEFAULT 1,
  "updated_at" timestamp NOT NULL DEFAULT now(),
  CONSTRAINT "final_exam_room" FOREIGN KEY ("room_id") REFERENCES "public"."rooms"("id") ON DELETE no action ON UPDATE no action,
  CONSTRAINT "final_exam_term" FOREIGN KEY ("term_id") REFERENCES "public"."terms"("id") ON DELETE no action ON UPDATE no action
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "final_exams_term_course_idx"
  ON "final_exams" ("term_id", "course_code");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "final_exams_term_room_idx"
  ON "final_exams" ("term_id", "room_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "final_exams_term_date_idx"
  ON "final_exams" ("term_id", "exam_date");
--> statement-breakpoint
INSERT INTO "update" ("table_name")
VALUES ('final_exams')
ON CONFLICT DO NOTHING;
