CREATE TABLE IF NOT EXISTS contributions (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id integer REFERENCES admin_users (id),
  submitter_name varchar(100),
  entity_type varchar(32) NOT NULL,
  entity_id integer NOT NULL,
  entity_label text NOT NULL,
  source varchar(32) NOT NULL,
  proposal_id integer REFERENCES edit_proposals (id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS contributions_user_created_idx
  ON contributions (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS contributions_created_at_idx
  ON contributions (created_at DESC);
