CREATE TABLE IF NOT EXISTS "organizations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organizations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"category" varchar(24) NOT NULL,
	"building_id" integer,
	"room_id" integer,
	"lat" double precision,
	"lon" double precision,
	"description" text,
	"website_link" text,
	"facebook_link" text,
	"email" text,
	"image_url" text,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
