CREATE TABLE IF NOT EXISTS "jeepney_routes" (
  "id" varchar(64) PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "description" text NOT NULL,
  "direction_note" text,
  "color" varchar(16) NOT NULL,
  "fare_regular" double precision NOT NULL,
  "fare_discounted" double precision NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "version" integer NOT NULL DEFAULT 1,
  "updated_at" timestamp NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "jeepney_stops" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "route_id" varchar(64) NOT NULL REFERENCES "jeepney_routes"("id") ON DELETE CASCADE,
  "name" varchar(160) NOT NULL,
  "description" text NOT NULL,
  "lat" double precision NOT NULL,
  "lon" double precision NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "version" integer NOT NULL DEFAULT 1,
  "updated_at" timestamp NOT NULL DEFAULT now(),
  CONSTRAINT "jeepney_stops_route_sort_order" UNIQUE ("route_id", "sort_order")
);
--> statement-breakpoint
INSERT INTO "jeepney_routes" ("id", "name", "description", "direction_note", "color", "fare_regular", "fare_discounted")
VALUES
  ('kaliwa-kanan', 'Kaliwa / Kanan', 'Loop between Olivarez Plaza in Los Baños town and the UPLB academic core, passing Raymundo Gate, the Main Library, the dormitories, and CEAT.', 'Kaliwa and Kanan are the same loop; the name says which way the jeep turns after entering the UPLB gate. Kaliwa turns left and follows the stops as listed (Carabao Park / DevCom first); Kanan turns right and serves the same stops in reverse (Carabao Park / Landbank first).', '#dc2626', 13, 11),
  ('forestry', 'Forestry', 'Connects the campus core to the upper Forestry campus: from the Forestry jeep terminal past the Main Library area, Narra Bridge, and the University Health Service, climbing to the College of Forestry and Natural Resources.', NULL, '#15803d', 13, 11)
ON CONFLICT ("id") DO NOTHING;
--> statement-breakpoint
INSERT INTO "jeepney_stops" ("route_id", "name", "description", "lat", "lon", "sort_order")
VALUES
  ('kaliwa-kanan', 'Olivarez Plaza Mall', 'Town-side terminal and common transfer point near Olivarez Plaza.', 14.17903, 121.23908, 1),
  ('kaliwa-kanan', 'Robinsons Town Mall', 'Town-side stop beside Robinsons Los Baños.', 14.177349211032917, 121.24242089688644, 2),
  ('kaliwa-kanan', 'Carabao Park / DevCom', 'Campus-core stop by Carabao Park and the College of Development Communication.', 14.167680673655115, 121.24302990984792, 3),
  ('kaliwa-kanan', 'Raymundo Gate', 'Gate-side stop along Raymundo Road, linking town and campus.', 14.16773707639881, 121.2416075132719, 4),
  ('kaliwa-kanan', 'CAP-CSI', 'Stop near the College of Arts and Sciences and campus service offices.', 14.167227355646022, 121.24044598783846, 5),
  ('kaliwa-kanan', 'Sacay', 'Central-campus stop on the route between Raymundo Gate and the library.', 14.166436241690047, 121.23861696327558, 6),
  ('kaliwa-kanan', 'Main Library', 'Stop beside the UPLB Main Library and the central academic core.', 14.165440954550126, 121.2386041983236, 7),
  ('kaliwa-kanan', 'Graduate School / Umali', 'Stop serving the Graduate School and the Umali Hall area.', 14.163742377049818, 121.23998877527784, 8),
  ('kaliwa-kanan', 'Women''s Dormitory', 'Stop by the Women''s Dormitory residence halls.', 14.162362067987052, 121.24056837513993, 9),
  ('kaliwa-kanan', 'Men''s Dormitory', 'Stop by the Men''s Dormitory residence halls.', 14.16091203484906, 121.2412408051354, 10),
  ('kaliwa-kanan', 'Baker Hall', 'Stop near Baker Hall and nearby student services.', 14.161219041586817, 121.24257006568956, 11),
  ('kaliwa-kanan', 'Animal Husbandry', 'Stop serving the Animal and Dairy Sciences area.', 14.15989413929804, 121.24366990769977, 12),
  ('kaliwa-kanan', 'Agronomy Building', 'Stop close to the Agronomy academic buildings.', 14.160182373364517, 121.2443733752706, 13),
  ('kaliwa-kanan', 'College of Engineering and Agro-Industrial Technology', 'Stop for CEAT classrooms and laboratories.', 14.16087221013792, 121.24495080555562, 14),
  ('kaliwa-kanan', 'Senior''s Social Garden', 'Stop beside the Senior''s Social Garden in the campus core.', 14.162690186117826, 121.2438403651636, 15),
  ('kaliwa-kanan', 'Headquarters', 'Stop near the UPLB administrative headquarters area.', 14.16352431907233, 121.2437220269563, 16),
  ('kaliwa-kanan', 'St. Therese / Math Building', 'Stop near St. Therese and Mathematics classroom buildings.', 14.165120117289403, 121.24456008780996, 17),
  ('kaliwa-kanan', 'Makiling School', 'Stop beside the UP Rural High School / Makiling School area.', 14.165744564457338, 121.24426410223518, 18),
  ('kaliwa-kanan', 'Carabao Park / Landbank', 'Campus-core stop by Carabao Park and the LandBank area.', 14.167026218728786, 121.24373658223566, 19),
  ('kaliwa-kanan', 'Olivarez Plaza Mall', 'Town-side terminal and common transfer point near Olivarez Plaza.', 14.17903, 121.23908, 20),
  ('forestry', 'Forestry Jeep Terminal', 'Terminal for the uphill route to the Forestry campus.', 14.16809105957495, 121.24248142545251, 1),
  ('forestry', 'CEM Jeepney Stop', 'Stop serving the College of Economics and Management area.', 14.167744858385788, 121.24160128212628, 2),
  ('forestry', 'OVCRE Annex Building', 'Stop near the Office of the Vice Chancellor for Research and Extension annex.', 14.167161010311109, 121.24043389915563, 3),
  ('forestry', 'Narra Bridge', 'Stop by Narra Bridge on the approach to upper campus.', 14.164723828661357, 121.23847671766336, 4),
  ('forestry', 'Maria Makiling Statue', 'Stop beside the Maria Makiling statue along the Forestry route.', 14.163961515861006, 121.23821626095294, 5),
  ('forestry', 'UP University Health Service', 'Stop serving the University Health Service.', 14.161996442247391, 121.23868610580267, 6),
  ('forestry', 'Forest Biological Sciences Building', 'Upper-campus stop near the Forest Biological Sciences Building.', 14.154716857167369, 121.2360341113496, 7)
ON CONFLICT ("route_id", "sort_order") DO NOTHING;
--> statement-breakpoint
INSERT INTO "update" ("table_name")
VALUES ('jeepney_routes')
ON CONFLICT ("table_name") DO UPDATE SET "sync_key" = gen_random_uuid();
