-- Campus flora: notable trees and labelled specimens.
--
-- Species and specimens are separate tables from the start even though phase 1
-- only shows one specimen per notable tree. Phase 2 relaxes the `is_notable`
-- filter and adds many specimens per species to build a distribution view;
-- collapsing both into one table now would make that a migration rewrite.
CREATE TABLE IF NOT EXISTS "flora_species" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flora_species_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scientific_name" text NOT NULL,
	"family" text,
	-- Filipino and English names both live here; there is no single "the" common
	-- name for most of these.
	"common_names" text[],
	"description" text,
	"image_url" text,
	"conservation_status" varchar(32),
	"is_native" boolean,
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "flora_species_scientific_name_unique" UNIQUE ("scientific_name")
);

CREATE TABLE IF NOT EXISTS "flora_specimens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flora_specimens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"species_id" integer NOT NULL REFERENCES "flora_species"("id") ON DELETE CASCADE,
	"lat" double precision NOT NULL,
	"lon" double precision NOT NULL,
	"tag_number" varchar(32),
	"planted_year" integer,
	"notes" text,
	"is_notable" boolean DEFAULT false NOT NULL,
	-- Provenance is not bookkeeping. Room TBA publishes campus data as CC-BY 4.0
	-- and many iNaturalist observations are CC-BY-NC, which is incompatible.
	-- Recording the licence per row is what lets a bulk CC-BY export exclude the
	-- rows it may not carry, instead of the open-data claim quietly becoming false.
	"source" varchar(32) DEFAULT 'manual' NOT NULL,
	"source_ref" text,
	"source_licence" varchar(64),
	"version" integer DEFAULT 1 NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

-- Phase 1 renders the notable pins; phase 2 pages a species' full distribution.
CREATE INDEX IF NOT EXISTS "flora_specimens_species_idx" ON "flora_specimens" ("species_id");
CREATE INDEX IF NOT EXISTS "flora_specimens_notable_idx" ON "flora_specimens" ("is_notable");

-- Client-side PGlite sync needs a registry row per cached table.
INSERT INTO "update" ("table_name")
VALUES ('flora_species'), ('flora_specimens')
ON CONFLICT ("table_name") DO UPDATE
SET "sync_key" = gen_random_uuid();
