-- In-app feedback box (#881): free-text messages from anyone using the app.
-- Deliberately stores no IP and no required email — the optional `contact` is
-- whatever the sender chose to type. Server-only table: it is never synced to
-- the client PGlite cache, so no `update` registry row.
CREATE TABLE IF NOT EXISTS "feedback" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "feedback_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"message" text NOT NULL,
	"contact" text,
	"screen" text,
	"app_version" text,
	"was_online" boolean,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "feedback_created_at_idx" ON "feedback" ("created_at" DESC);
