-- "Jeep is here" reports at transit stops: riders tap once when a jeep passes,
-- and the stop panel turns recent taps into "Last jeep reported N min ago" and
-- a rough "About every N min lately". Anonymous: `device_id` is a random UUID
-- the browser keeps in localStorage, used only for the per-device cooldown. No
-- IP, account, or location is stored. Server-only (never synced to PGlite).
-- Rows older than a day carry no signal and are pruned by /api/transit/reports.
-- No FK to jeepney_routes: bundled bus routes live only in code.
CREATE TABLE IF NOT EXISTS "jeep_reports" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "jeep_reports_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"route_id" varchar(64) NOT NULL,
	"stop_key" varchar(32) NOT NULL,
	"direction" varchar(8),
	"device_id" varchar(64) NOT NULL,
	"is_full" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- The stop panel reads one stop's last hour; the route page reads one route's.
CREATE INDEX IF NOT EXISTS "jeep_reports_stop_created_idx" ON "jeep_reports" ("stop_key", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "jeep_reports_route_created_idx" ON "jeep_reports" ("route_id", "created_at" DESC);
-- Cooldown lookup: this device's latest report.
CREATE INDEX IF NOT EXISTS "jeep_reports_device_created_idx" ON "jeep_reports" ("device_id", "created_at" DESC);
