// AUTO-GENERATED by scripts/generate-pglite-schema.ts — do not edit.
// Regenerate with: bun run generate:pglite-schema
// Source of truth: drizzle/schema.ts (+ LOCAL_ONLY overlay in the generator).

export const PGLITE_INIT_SQL = `
CREATE TABLE IF NOT EXISTS "buildings" (
  "id" integer PRIMARY KEY,
  "building_name" varchar(100) NOT NULL,
  "lon" double precision NOT NULL,
  "type" text DEFAULT 'non-admin' NOT NULL,
  "lat" double precision NOT NULL,
  "directions" text NOT NULL,
  "image_url" text,
  "cr_facilities" text[],
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "rooms_fetched" boolean DEFAULT false NOT NULL
);
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "building_name" varchar(100);
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "lon" double precision;
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "type" text DEFAULT 'non-admin' NOT NULL;
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "lat" double precision;
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "directions" text;
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "cr_facilities" text[];
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "buildings" ADD COLUMN IF NOT EXISTS "rooms_fetched" boolean DEFAULT false NOT NULL;
CREATE TABLE IF NOT EXISTS "colleges" (
  "id" integer PRIMARY KEY,
  "college_name" varchar(100) NOT NULL,
  "website_link" text,
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "rooms_fetched" boolean DEFAULT false NOT NULL
);
ALTER TABLE "colleges" ADD COLUMN IF NOT EXISTS "college_name" varchar(100);
ALTER TABLE "colleges" ADD COLUMN IF NOT EXISTS "website_link" text;
ALTER TABLE "colleges" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "colleges" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "colleges" ADD COLUMN IF NOT EXISTS "rooms_fetched" boolean DEFAULT false NOT NULL;
CREATE TABLE IF NOT EXISTS "classes" (
  "id" integer PRIMARY KEY,
  "course_code" varchar(16),
  "section" varchar(16),
  "type" varchar(12),
  "schedule" text[],
  "room_id" integer,
  "course_title" text,
  "term_id" integer,
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "directions" text
);
ALTER TABLE "classes" ADD COLUMN IF NOT EXISTS "course_code" varchar(16);
ALTER TABLE "classes" ADD COLUMN IF NOT EXISTS "section" varchar(16);
ALTER TABLE "classes" ADD COLUMN IF NOT EXISTS "type" varchar(12);
ALTER TABLE "classes" ADD COLUMN IF NOT EXISTS "schedule" text[];
ALTER TABLE "classes" ADD COLUMN IF NOT EXISTS "room_id" integer;
ALTER TABLE "classes" ADD COLUMN IF NOT EXISTS "course_title" text;
ALTER TABLE "classes" ADD COLUMN IF NOT EXISTS "term_id" integer;
ALTER TABLE "classes" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "classes" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "classes" ADD COLUMN IF NOT EXISTS "directions" text;
CREATE TABLE IF NOT EXISTS "final_exams" (
  "id" integer PRIMARY KEY,
  "term_id" integer NOT NULL,
  "course_code" varchar(16) NOT NULL,
  "section" varchar(16),
  "course_title" text,
  "room_id" integer,
  "exam_date" text NOT NULL,
  "starts_at" text NOT NULL,
  "ends_at" text NOT NULL,
  "source" varchar(64) NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "final_exams" ADD COLUMN IF NOT EXISTS "term_id" integer;
ALTER TABLE "final_exams" ADD COLUMN IF NOT EXISTS "course_code" varchar(16);
ALTER TABLE "final_exams" ADD COLUMN IF NOT EXISTS "section" varchar(16);
ALTER TABLE "final_exams" ADD COLUMN IF NOT EXISTS "course_title" text;
ALTER TABLE "final_exams" ADD COLUMN IF NOT EXISTS "room_id" integer;
ALTER TABLE "final_exams" ADD COLUMN IF NOT EXISTS "exam_date" text;
ALTER TABLE "final_exams" ADD COLUMN IF NOT EXISTS "starts_at" text;
ALTER TABLE "final_exams" ADD COLUMN IF NOT EXISTS "ends_at" text;
ALTER TABLE "final_exams" ADD COLUMN IF NOT EXISTS "source" varchar(64);
ALTER TABLE "final_exams" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "final_exams" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
CREATE TABLE IF NOT EXISTS "dorms" (
  "id" integer PRIMARY KEY,
  "dorm_name" text NOT NULL,
  "short_name" varchar(48),
  "lat" double precision,
  "lon" double precision,
  "gender" text NOT NULL,
  "capacity" integer,
  "managing_office" text,
  "contact_email" text,
  "amenities" text[],
  "osm_link" text,
  "description" text,
  "is_up_managed" boolean DEFAULT true,
  "price_range" text,
  "contact_phone" varchar(20)[],
  "facebook_link" text,
  "image_url" text,
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "dorm_name" text;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "short_name" varchar(48);
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "lat" double precision;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "lon" double precision;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "gender" text;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "capacity" integer;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "managing_office" text;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "contact_email" text;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "amenities" text[];
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "osm_link" text;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "is_up_managed" boolean DEFAULT true;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "price_range" text;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "contact_phone" varchar(20)[];
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "facebook_link" text;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "dorms" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
CREATE TABLE IF NOT EXISTS "organizations" (
  "id" integer PRIMARY KEY,
  "name" text NOT NULL,
  "category" varchar(24) NOT NULL,
  "building_id" integer,
  "room_id" integer,
  "lat" double precision,
  "lon" double precision,
  "description" text,
  "website_link" text,
  "facebook_link" text,
  "email" text,
  "image_url" text,
  "bio" text,
  "org_type" varchar(32),
  "established_year" varchar(8),
  "member_count" varchar(16),
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "name" text;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "category" varchar(24);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "building_id" integer;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "room_id" integer;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "lat" double precision;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "lon" double precision;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "website_link" text;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "facebook_link" text;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "email" text;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "bio" text;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "org_type" varchar(32);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "established_year" varchar(8);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "member_count" varchar(16);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
CREATE TABLE IF NOT EXISTS "places" (
  "id" integer PRIMARY KEY,
  "name" text NOT NULL,
  "category" varchar(24) NOT NULL,
  "lat" double precision,
  "lon" double precision,
  "description" text,
  "hours" text,
  "website_link" text,
  "facebook_link" text,
  "image_url" text,
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "places" ADD COLUMN IF NOT EXISTS "name" text;
ALTER TABLE "places" ADD COLUMN IF NOT EXISTS "category" varchar(24);
ALTER TABLE "places" ADD COLUMN IF NOT EXISTS "lat" double precision;
ALTER TABLE "places" ADD COLUMN IF NOT EXISTS "lon" double precision;
ALTER TABLE "places" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "places" ADD COLUMN IF NOT EXISTS "hours" text;
ALTER TABLE "places" ADD COLUMN IF NOT EXISTS "website_link" text;
ALTER TABLE "places" ADD COLUMN IF NOT EXISTS "facebook_link" text;
ALTER TABLE "places" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE "places" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "places" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
CREATE TABLE IF NOT EXISTS "room_positions" (
  "id" integer PRIMARY KEY,
  "floor" integer NOT NULL,
  "pos_x" numeric NOT NULL,
  "pos_y" numeric NOT NULL,
  "updated_at" text NOT NULL,
  "room_id" integer NOT NULL
);
ALTER TABLE "room_positions" ADD COLUMN IF NOT EXISTS "floor" integer;
ALTER TABLE "room_positions" ADD COLUMN IF NOT EXISTS "pos_x" numeric;
ALTER TABLE "room_positions" ADD COLUMN IF NOT EXISTS "pos_y" numeric;
ALTER TABLE "room_positions" ADD COLUMN IF NOT EXISTS "updated_at" text;
ALTER TABLE "room_positions" ADD COLUMN IF NOT EXISTS "room_id" integer;
CREATE TABLE IF NOT EXISTS "divisions" (
  "id" integer PRIMARY KEY,
  "division_name" varchar(100) NOT NULL,
  "college_id" integer,
  "website_link" text,
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "rooms_fetched" boolean DEFAULT false NOT NULL
);
ALTER TABLE "divisions" ADD COLUMN IF NOT EXISTS "division_name" varchar(100);
ALTER TABLE "divisions" ADD COLUMN IF NOT EXISTS "college_id" integer;
ALTER TABLE "divisions" ADD COLUMN IF NOT EXISTS "website_link" text;
ALTER TABLE "divisions" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "divisions" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "divisions" ADD COLUMN IF NOT EXISTS "rooms_fetched" boolean DEFAULT false NOT NULL;
CREATE TABLE IF NOT EXISTS "rooms" (
  "id" integer PRIMARY KEY,
  "room_code" text NOT NULL,
  "directions" text,
  "building_id" integer,
  "college_id" integer,
  "division_id" integer,
  "image_url" text,
  "category" varchar(24),
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "classes_fetched" boolean DEFAULT false NOT NULL
);
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "room_code" text;
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "directions" text;
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "building_id" integer;
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "college_id" integer;
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "division_id" integer;
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "category" varchar(24);
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "rooms" ADD COLUMN IF NOT EXISTS "classes_fetched" boolean DEFAULT false NOT NULL;
CREATE TABLE IF NOT EXISTS "events" (
  "id" integer PRIMARY KEY,
  "slug" varchar(120) NOT NULL,
  "title" varchar(160) NOT NULL,
  "description" text,
  "category" text DEFAULT 'other' NOT NULL,
  "starts_at" text NOT NULL,
  "ends_at" text NOT NULL,
  "timezone" varchar(64) DEFAULT 'Asia/Manila' NOT NULL,
  "recurrence" text DEFAULT 'none' NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "source_url" text,
  "image_url" text,
  "priority" integer DEFAULT 0 NOT NULL,
  "include_in_seo" boolean DEFAULT false NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "status" varchar(16) DEFAULT 'past' NOT NULL,
  "occurrence_starts_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "occurrence_ends_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "slug" varchar(120);
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "title" varchar(160);
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "category" text DEFAULT 'other' NOT NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "starts_at" text;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "ends_at" text;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "timezone" varchar(64) DEFAULT 'Asia/Manila' NOT NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "recurrence" text DEFAULT 'none' NOT NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "source_url" text;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "image_url" text;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "priority" integer DEFAULT 0 NOT NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "include_in_seo" boolean DEFAULT false NOT NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "status" varchar(16) DEFAULT 'past' NOT NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "occurrence_starts_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS "occurrence_ends_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
CREATE TABLE IF NOT EXISTS "event_locations" (
  "id" integer PRIMARY KEY,
  "event_id" integer NOT NULL,
  "anchor_type" text NOT NULL,
  "building_id" integer,
  "dorm_id" integer,
  "label" text NOT NULL,
  "lat" double precision,
  "lon" double precision,
  "highlight_priority" integer DEFAULT 0 NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "is_primary" boolean DEFAULT false NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "resolved_lat" double precision,
  "resolved_lon" double precision,
  "resolved_label" text,
  "building_name" text,
  "dorm_name" text
);
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "event_id" integer;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "anchor_type" text;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "building_id" integer;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "dorm_id" integer;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "label" text;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "lat" double precision;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "lon" double precision;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "highlight_priority" integer DEFAULT 0 NOT NULL;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0 NOT NULL;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "is_primary" boolean DEFAULT false NOT NULL;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "resolved_lat" double precision;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "resolved_lon" double precision;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "resolved_label" text;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "building_name" text;
ALTER TABLE "event_locations" ADD COLUMN IF NOT EXISTS "dorm_name" text;
CREATE TABLE IF NOT EXISTS "event_routes" (
  "id" integer PRIMARY KEY,
  "event_id" integer NOT NULL,
  "name" varchar(120) NOT NULL,
  "description" text,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "event_routes" ADD COLUMN IF NOT EXISTS "event_id" integer;
ALTER TABLE "event_routes" ADD COLUMN IF NOT EXISTS "name" varchar(120);
ALTER TABLE "event_routes" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "event_routes" ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0 NOT NULL;
ALTER TABLE "event_routes" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
CREATE TABLE IF NOT EXISTS "event_route_stops" (
  "id" integer PRIMARY KEY,
  "route_id" integer NOT NULL,
  "event_location_id" integer,
  "label" text NOT NULL,
  "lat" double precision,
  "lon" double precision,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "resolved_lat" double precision,
  "resolved_lon" double precision,
  "resolved_label" text
);
ALTER TABLE "event_route_stops" ADD COLUMN IF NOT EXISTS "route_id" integer;
ALTER TABLE "event_route_stops" ADD COLUMN IF NOT EXISTS "event_location_id" integer;
ALTER TABLE "event_route_stops" ADD COLUMN IF NOT EXISTS "label" text;
ALTER TABLE "event_route_stops" ADD COLUMN IF NOT EXISTS "lat" double precision;
ALTER TABLE "event_route_stops" ADD COLUMN IF NOT EXISTS "lon" double precision;
ALTER TABLE "event_route_stops" ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0 NOT NULL;
ALTER TABLE "event_route_stops" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "event_route_stops" ADD COLUMN IF NOT EXISTS "resolved_lat" double precision;
ALTER TABLE "event_route_stops" ADD COLUMN IF NOT EXISTS "resolved_lon" double precision;
ALTER TABLE "event_route_stops" ADD COLUMN IF NOT EXISTS "resolved_label" text;
CREATE TABLE IF NOT EXISTS "jeepney_routes" (
  "id" varchar(64) PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "description" text NOT NULL,
  "direction_note" text,
  "color" varchar(16) NOT NULL,
  "fare_regular" double precision NOT NULL,
  "fare_discounted" double precision NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "jeepney_routes" ADD COLUMN IF NOT EXISTS "name" varchar(120);
ALTER TABLE "jeepney_routes" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "jeepney_routes" ADD COLUMN IF NOT EXISTS "direction_note" text;
ALTER TABLE "jeepney_routes" ADD COLUMN IF NOT EXISTS "color" varchar(16);
ALTER TABLE "jeepney_routes" ADD COLUMN IF NOT EXISTS "fare_regular" double precision;
ALTER TABLE "jeepney_routes" ADD COLUMN IF NOT EXISTS "fare_discounted" double precision;
ALTER TABLE "jeepney_routes" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE "jeepney_routes" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "jeepney_routes" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
CREATE TABLE IF NOT EXISTS "jeepney_stops" (
  "id" integer PRIMARY KEY,
  "route_id" varchar(64) NOT NULL,
  "name" varchar(160) NOT NULL,
  "description" text NOT NULL,
  "lat" double precision NOT NULL,
  "lon" double precision NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "is_active" boolean DEFAULT true NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE "jeepney_stops" ADD COLUMN IF NOT EXISTS "route_id" varchar(64);
ALTER TABLE "jeepney_stops" ADD COLUMN IF NOT EXISTS "name" varchar(160);
ALTER TABLE "jeepney_stops" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "jeepney_stops" ADD COLUMN IF NOT EXISTS "lat" double precision;
ALTER TABLE "jeepney_stops" ADD COLUMN IF NOT EXISTS "lon" double precision;
ALTER TABLE "jeepney_stops" ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0 NOT NULL;
ALTER TABLE "jeepney_stops" ADD COLUMN IF NOT EXISTS "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE "jeepney_stops" ADD COLUMN IF NOT EXISTS "version" integer DEFAULT 1 NOT NULL;
ALTER TABLE "jeepney_stops" ADD COLUMN IF NOT EXISTS "updated_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
CREATE TABLE IF NOT EXISTS "aliases" (
  "id" integer PRIMARY KEY,
  "alias" text NOT NULL,
  "normalized_alias" text NOT NULL,
  "target_type" varchar(16) NOT NULL,
  "target_id" integer NOT NULL,
  "source" varchar(32),
  "confidence" varchar(16) DEFAULT 'unverified' NOT NULL,
  "created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "building_name" text
);
ALTER TABLE "aliases" ADD COLUMN IF NOT EXISTS "alias" text;
ALTER TABLE "aliases" ADD COLUMN IF NOT EXISTS "normalized_alias" text;
ALTER TABLE "aliases" ADD COLUMN IF NOT EXISTS "target_type" varchar(16);
ALTER TABLE "aliases" ADD COLUMN IF NOT EXISTS "target_id" integer;
ALTER TABLE "aliases" ADD COLUMN IF NOT EXISTS "source" varchar(32);
ALTER TABLE "aliases" ADD COLUMN IF NOT EXISTS "confidence" varchar(16) DEFAULT 'unverified' NOT NULL;
ALTER TABLE "aliases" ADD COLUMN IF NOT EXISTS "created_at" text DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE "aliases" ADD COLUMN IF NOT EXISTS "building_name" text;
`;
