/**
 * Decides whether a build is allowed to rewrite the committed
 * src/generated/release-timestamps.json.
 *
 * The file is committed because it is the offline fallback when the GitHub
 * releases API is unreachable or rate limited. It is also regenerated by
 * `bun run build`, and those two facts together made it conflict on nearly
 * every branch (#925): a local build rewrote it, the diff got swept into
 * whatever PR that developer was on, and the next branch to do the same
 * conflicted. Every commit touching the file so far has been an unrelated
 * feature or fix PR.
 *
 * CI and Vercel builds still refresh it, so production ships exact timestamps.
 * Only the developer working tree is left alone. The committed copy is allowed
 * to lag: when it lacks a version, the UI already falls back to the date parsed
 * from the CHANGELOG heading.
 */
export function canWriteReleaseTimestamps(
  env: Record<string, string | undefined>,
): boolean {
  // Escape hatch for deliberately refreshing the committed fallback.
  if (env.RELEASE_TIMESTAMPS_WRITE === "1") return true;
  // GitHub Actions sets "true", Vercel sets "1". Neither commits the result.
  return env.CI === "true" || env.CI === "1";
}
