/**
 * Bootstrap a fork: rewrite src/campus.config.ts for your campus.
 *
 * Prompts for the campus-specific surface (name, URL, map center/bounds/zoom,
 * terrain, transit) and regenerates the config file from a template so it
 * stays typechecked. Everything else a fork replaces (seed data, transit
 * routes, importers) is listed by `bun run fork:check`.
 *
 * Usage:
 *   bun run fork:init             # interactive
 *   bun run fork:init --defaults  # accept every fallback (smoke test / CI)
 *   bun run fork:init --force     # allow a dirty git tree
 *
 * Idempotent: re-running with the same answers writes the same file. A dirty
 * tree is refused (except campus.config.ts itself) so the rewrite stays easy
 * to review and revert.
 */
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import readline from "node:readline/promises";

const CONFIG_PATH = "src/campus.config.ts";
const force = process.argv.includes("--force");
const useDefaults = process.argv.includes("--defaults");

const dirty = execSync("git status --porcelain", { encoding: "utf8" })
  .trim()
  .split("\n")
  .filter((line) => line && !line.endsWith(CONFIG_PATH));
if (dirty.length > 0 && !force) {
  console.error(
    "Refusing to run on a dirty git tree so the config rewrite is easy to review. Commit or stash first, or pass --force.",
  );
  process.exit(1);
}

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

async function ask(question: string, fallback: string): Promise<string> {
  if (useDefaults) return fallback;
  const answer = (await rl.question(`${question} [${fallback}]: `)).trim();
  return answer || fallback;
}

async function askNumber(question: string, fallback: number): Promise<number> {
  const raw = await ask(question, String(fallback));
  const value = Number(raw);
  if (!Number.isFinite(value)) {
    console.error(`  "${raw}" is not a number; using ${fallback}.`);
    return fallback;
  }
  return value;
}

async function askBool(question: string, fallback: boolean): Promise<boolean> {
  const raw = await ask(`${question} (y/n)`, fallback ? "y" : "n");
  return /^y/i.test(raw);
}

const name = await ask("Campus app name", "Room TBA");
const url = await ask("Site URL", "https://rooms.example.edu");
const lat = await askNumber("Map center latitude", 14.163237);
const lng = await askNumber("Map center longitude", 121.241259);
const west = await askNumber("Bounds west longitude", lng - 0.08);
const south = await askNumber("Bounds south latitude", lat - 0.06);
const east = await askNumber("Bounds east longitude", lng + 0.08);
const north = await askNumber("Bounds north latitude", lat + 0.06);
const zoom = await askNumber("Default zoom", 15.8);
const terrainOn = await askBool("Enable 3D terrain (needs MapTiler)", false);
const transitOn = await askBool("Enable campus transit overlay", false);
rl.close();

/** The template mirrors the committed campus.config.ts structure — keep the
 * two in sync when adding config sections. */
const config = `/**
 * Single source of truth for campus-specific config.
 *
 * Generated by \`bun run fork:init\` — edit freely, but keep the exported
 * shapes: the app, scripts, and E2E suite import them. Run
 * \`bun run fork:check\` afterwards to catch remaining upstream strings.
 *
 * Values are plain literals so astro.config.mjs can import this module at
 * config-eval time (no process.env reads at module top level).
 */

export const campusSite = {
  url: ${JSON.stringify(url)},
  name: ${JSON.stringify(name)},
  title: ${JSON.stringify(`${name} | Find rooms and buildings on campus`)},
  description: ${JSON.stringify(
    `${name} helps students find rooms and buildings across campus.`,
  )},
} as const;

export const campusMap: {
  maxBounds: [[number, number], [number, number]];
  defaultCamera: {
    center: [number, number];
    zoom: number;
    pitch: number;
    bearing: number;
  };
} = {
  /** [lng, lat] — west/south corner, then east/north corner. */
  maxBounds: [
    [${west}, ${south}],
    [${east}, ${north}],
  ],
  /** Default camera: center [lng, lat], zoom, pitch (0 = top-down, 60 = tilted 3D), bearing. */
  defaultCamera: {
    center: [${lng}, ${lat}],
    zoom: ${zoom},
    pitch: 60,
    bearing: 0,
  },
};

export const campusTerrain: {
  enabled: boolean;
  demTilesUrl: string;
  maxBounds: [[number, number], [number, number]];
  camera: {
    center: [number, number];
    zoom: number;
    pitch: number;
    bearing: number;
  };
} = {
  /** 3D terrain (raster-dem + hillshade). false = flat map, no terrain controls. */
  enabled: ${terrainOn},
  /** TileJSON for the elevation source; __MAPTILER_KEY__ is replaced with PUBLIC_MAPTILER_KEY at runtime. */
  demTilesUrl:
    "https://api.maptiler.com/tiles/terrain-rgb-v2/tiles.json?key=__MAPTILER_KEY__",
  /** [lng, lat] corners the terrain view may cover — tune to your landscape. */
  maxBounds: [
    [${west}, ${south}],
    [${east}, ${north}],
  ],
  /** Camera the map flies to when terrain mode turns on — tune to your landscape. */
  camera: { center: [${lng}, ${lat}], zoom: ${zoom - 2.5}, pitch: 68, bearing: 0 },
};

export const campusTransit: {
  enabled: boolean;
  label: string;
  routeDataModule: string;
} = {
  /** Campus transit overlay: map layer, sidebar browse tab, /transit/ links, sitemap entries. */
  enabled: ${transitOn},
  /** Menu / browse-tab label; title case and singular copy are derived from it. */
  label: "Campus transit",
  /** Bundled route/stop data a fork replaces (runtime rows come from the transit tables). */
  routeDataModule: "src/constants/jeepney-routes.ts",
};

/** Reference points inside campus bounds for the E2E suite (seeded by scripts/e2e-reset-db.ts). */
export const campusTestFixtures = {
  buildingLat: ${lat},
  buildingLon: ${lng},
  dormLat: ${lat + 0.0005},
  dormLon: ${lng + 0.0008},
} as const;

export const campusCommunity = {
  // TODO(fork): point these at your own community (fork:check will not flag
  // placeholders — review them yourself).
  orgUrl: ${JSON.stringify(url)},
  githubUrl: "https://github.com/your-org/your-fork",
  discordUrl: "",
  osaOrganizationsUrl: "",
  /** Messenger group chat invites (targets for redirect workers). */
  messengerContributeTarget: "",
  messengerMaintainTarget: "",
  /** Short links on a community subdomain (Cloudflare Worker). Delete if unused. */
  messengerShortContributeUrl: "",
  messengerShortMaintainUrl: "",
} as const;
`;

writeFileSync(CONFIG_PATH, config);
try {
  // Prompted values change line lengths; let the repo formatter settle them.
  execSync(`bunx biome format --write ${CONFIG_PATH}`, { stdio: "ignore" });
} catch {
  console.warn("biome format failed — run `bun run lint:fix` yourself.");
}
console.log(`Wrote ${CONFIG_PATH}.`);
console.log(
  "Next: bun run fork:check (remaining upstream strings), replace seed data, and see README § Fork this for your campus.",
);
