"""Regenerate src/constants/print-brand.ts for the printable jeepney map.

pdf-lib only ships the 14 standard fonts and has no QR encoder, so the brand
pieces are baked once: Raleway Bold outlines for the fixed headings, the QR
module grid for the print link, and a small copy of public/logo.png.

    python3 scripts/generate-print-brand.py path/to/Raleway[wght].ttf

Needs fontTools, Pillow and qrcode (pip install fonttools pillow qrcode).
Run `bunx biome format --write src/constants/print-brand.ts` afterwards.
"""

import base64
import io
import json
import sys

import qrcode
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from PIL import Image

PRINT_URL = "https://room-tba.uplb.tools/?ref=print-map"
HEADINGS = ["UPLB Jeepney Routes", "Room TBA"]

font = instantiateVariableFont(TTFont(sys.argv[1]), {"wght": 700})
scale = 1000 / font["head"].unitsPerEm
cmap = font.getBestCmap()
glyphs = font.getGlyphSet()

paths = {}
for text in HEADINGS:
    pen = SVGPathPen(glyphs, ntos=lambda n: f"{n:.0f}")
    x = 0.0
    for ch in text:
        name = cmap[ord(ch)]
        # Font units are y-up; flip to the y-down space drawSvgPath expects.
        glyphs[name].draw(TransformPen(pen, (scale, 0, 0, -scale, x, 0)))
        x += glyphs[name].width * scale
    paths[text] = {"d": pen.getCommands(), "width": round(x)}

qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, border=0)
qr.add_data(PRINT_URL)
qr.make(fit=True)
rows = ["".join("1" if cell else "0" for cell in row) for row in qr.get_matrix()]

logo = Image.open("public/logo.png").convert("RGBA").resize((160, 160), Image.LANCZOS)
buf = io.BytesIO()
logo.save(buf, format="PNG", optimize=True)
logo_b64 = base64.b64encode(buf.getvalue()).decode()

with open("src/constants/print-brand.ts", "w") as out:
    out.write("// Generated by scripts/generate-print-brand.py. Do not edit by hand.\n\n")
    out.write(f"export const PRINT_MAP_URL = {json.dumps(PRINT_URL)};\n\n")
    out.write("/** QR modules for PRINT_MAP_URL, one string per row, 1 is dark. */\n")
    out.write(f"export const PRINT_MAP_QR: string[] = {json.dumps(rows, indent=2)};\n\n")
    out.write("/** Raleway Bold outlines, 1000 units per em, y-down, baseline at 0. */\n")
    keys = " | ".join(json.dumps(t) for t in HEADINGS)
    out.write(f"export const RALEWAY_BOLD_HEADINGS: Record<{keys}, {{ d: string; width: number }}> = {json.dumps(paths, indent=2)};\n\n")
    out.write("/** public/logo.png at 160 px, for pdf-lib embedPng. */\n")
    out.write(f"export const LOGO_PNG_BASE64 =\n  {json.dumps(logo_b64)};\n")
